version: '2'
services:
  postgres:
    build:
      context: .
      dockerfile: ./docker_compose/postgis/Dockerfile

  django:
    build:
      context: .
      dockerfile: ./docker_compose/django/development/Dockerfile
    command: django-admin.py runserver 0.0.0.0:8000 --settings=geonode.settings
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - geoserver
    links:
      - postgres
      - geoserver
    env_file:
      - ./scripts/docker/env/development/django.env

  geoserver:
    build:
      context: .
      dockerfile: ./docker_compose/geoserver/Dockerfile
    links:
      - postgres
    depends_on:
      - postgres
    volumes_from:
      - data_dir_conf
    ports:
      - "8080:8080"
    env_file:
      - ./scripts/docker/env/development/geoserver.env

  data_dir_conf:
    image: geonode/geoserver_data:2.9.x-oauth2
    container_name: geoserver_data_dir
    command: /bin/true
    volumes:
      - /geoserver_data/data

volumes:

  geoserver_data_dir:
