version: '2'
services:
  postgres:
    image: postgres
  web:
    build:
      context: .
      dockerfile: ./docker_compose/django/development/Dockerfile
    command: /start.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - geoserver
    links:
      - postgres
      - geoserver

  geoserver:
    build:
      context: .
      dockerfile: ./docker_compose/geoserver/Dockerfile
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - "8080:8080"
