apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: cyberspatial
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cyberspatial
    spec:
      containers:
      - image: geonode/nginx:geoserver
        name: cyberspatial
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
