apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: data-dir-conf
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: data-dir-conf
    spec:
      containers:
      - args:
        - /bin/true
        image: geonode/geoserver_data:2.9.x-oauth2
        name: geoserver_data_dir
        resources: {}
        volumeMounts:
        - mountPath: /geoserver_data/data
          name: data-dir-conf-claim0
      restartPolicy: Always
      volumes:
      - name: data-dir-conf-claim0
        persistentVolumeClaim:
          claimName: data-dir-conf-claim0
status: {}
