apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: django
    spec:
      containers:
      - image: gcr.io/cybereye-165816/django
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
        env:
        - name: DATABASE_URL
          value: postgres://postgres:postgres@postgres:5432/postgres
        - name: DJANGO_SETTINGS_MODULE
          value: njdca.settings
        - name: ALLOWED_HOSTS
          value: '[''django'',]'
        - name: C_FORCE_ROOT
          value: "1"
        - name: GEOSERVER_PUBLIC_LOCATION
          value: http://geonode/geoserver/
        - name: GEOSERVER_LOCATION
          value: http://geonode/geoserver/
        - name: SITEURL
          value: http://geonode/
        name: django
        ports:
        - containerPort: 8000
