apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: django
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: django
    spec:
      containers:
      - args:
        - /start.sh
        env:
        - name: DATABASE_URL
          value: postgres://postgres:postgres@postgres:5432/postgres
        - name: BROKER_URL
          value: amqp://guest:guest@rabbitmq:5672/
        - name: DJANGO_SETTINGS_MODULE
          value: njdca.settings
        - name: ALLOWED_HOSTS
          value: '[''django'',]'
        - name: C_FORCE_ROOT
          value: "1"
        - name: GEOSERVER_PUBLIC_LOCATION
          value: http://geonode/geoserver/
        - name: GEOSERVER_LOCATION
          value: http://geonode/geoserver/
        - name: SITEURL
          value: http://geonode/
        name: django
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
status: {}
