apiVersion: v1
kind: Service
metadata:
  labels:
    app: django
  name: django
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: django
