apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: geoserver
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: geoserver
    spec:
      containers:
      - env:
        - name: DOCKER_HOST
        - name: PUBLIC_PORT
          value: "80"
        - name: DOCKER_HOST_IP
        - name: DJANGO_URL
          value: http://django:8000/
        - name: GEOSERVER_PUBLIC_LOCATION
          value: http://geonode/geoserver/
        - name: GEOSERVER_LOCATION
          value: http://geoserver:8080/geoserver/
        - name: GEOSERVER_DATA_DIR
          value: /geoserver_data/data
        - name: SITEURL
          value: http://geonode/
        name: geoserver
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
