---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  labels:
    type: postgres
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  gcePersistentDisk:
    pdName: pg-data
    fsType: ext4
