---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: postgres
    spec:
      containers:
      - image: mdillon/postgis:9.6-alpine
        name: postgres
        ports:
          - containerPort: 5432
            name: postgres
        volumeMounts:
          - name: postgres-persistent-storage
            mountPath: /var/lib/postgresql/data
            subPath: data/
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: db-passwords
                key: djangouser
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-passwords
                key: djangouserpw
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-data