---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: geoserver-data
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: geoserver
