metadata:
  name: geonode
  labels:
    name: geonode
kind: Service
apiVersion: v1
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      name: http
      targetPort: 80
    - port: 443
      protocol: TCP
      name: https
      targetPort: 443
  selector:
    name: geonode
