---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
        io.kompose.service: rabbitmq
    spec:
      containers:
      - image: rabbitmq:3.6.10-alpine
        name: rabbitmq
        ports:
          - containerPort: 5672
            name: rabbitmq